# Generated by Django 4.1.3 on 2022-12-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Appblog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="", max_length=80),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=200),
        ),
    ]
